on:
  - push

env:
  DEBIAN_FRONTEND: nointeractive

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update APT
        run: apt-get update
      - name: Install APT Packages
        run: apt-get install -yq make zip rsync
      - name: Build a Package
        run: make -C browsers/firefox all
      - name: GH Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            browsers/firefox/dist/*.zip
